#!/bin/bash
set -e

die() {
    echo "$@"
    exit 1
}

cd $(dirname $0)
test -d .git || die Could not find git repository
test -d debian || die Could not find debian directory

pkg="$(grep '^Source:' debian/control | cut -d' ' -f2)"
author="$(git log -1 --pretty='%aN <%aE>')"
date="$(git log -1 --pretty='%aD')"
year="$(git log -1 --date='format:%Y' --pretty='%ad')"
version="$(git rev-list HEAD --count)"

rm -rf target
mkdir target
git archive --prefix="$pkg-$version/" HEAD | tar -x -C target
pushd "target/$pkg-$version"

cat > debian/changelog <<EOF
$pkg ($version) unstable; urgency=low

  * See git repository for changelog.

 -- $author  $date
EOF
{ echo "Copyright $year $author" ; cat debian/copyright.trailer ; } > debian/copyright
debuild -b

popd
mkdir -p target/archive/pool/main target/archive/dists/unstable/main/binary-amd64 target/archive/dists/unstable/main/binary-arm64
mv target/*.deb target/archive/pool/main/
apt-ftparchive -c apt-ftparchive/apt.conf generate apt-ftparchive/archive.conf
apt-ftparchive -c apt-ftparchive/apt.conf release target/archive/ | gpg --clear-sign > target/archive/dists/unstable/InRelease
