#!/bin/sh
set -e

die() {
    echo "$@"
    exit 1
}

cd $(dirname $0)
test -d .git || die Could not find git repository
test -d debian || die Could not find debian directory

pkg="$(grep '^Source:' debian/control | cut -d' ' -f2)"
author="$(git log -1 --pretty='%aN <%aE>')"
date="$(git log -1 --pretty='%aD')"
year="$(git log -1 --date='format:%Y' --pretty='%ad')"
version="$(git rev-list HEAD --count)"

target=target
rm -rf "$target"
mkdir "$target"
git archive --prefix="$pkg-$version/" HEAD | tar -x -C "$target"
cd "$target/$pkg-$version"

cat > debian/changelog <<EOF
$pkg ($version) unstable; urgency=low

  * See git repository for changelog.

 -- $author  $date
EOF
{ echo "Copyright $year $author" ; cat debian/copyright.trailer ; } > debian/copyright
debuild -b
