#!/bin/sh
set -e

if [ "$(id -u)" -ne 0 ]; then
    echo Must run as root. 1>&2
    exit 1
fi

conf="/etc/josh-backups.conf"
if ! [ -r "$conf" ]; then
    echo "Configure AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in $conf" 1>&2
    exit 1
fi
. "$conf"
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY RESTIC_PASSWORD

RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/josh-backup-restic-$(hostname)
export RESTIC_REPOSITORY

mkdir -p /var/cache/josh-backups
restic backup --cache-dir=/var/cache/josh-backups/ --exclude-caches --exclude='/home/*/.cache' --exclude='/home/*/Downloads' --one-file-system /home
restic forget --cache-dir=/var/cache/josh-backups/ --prune --keep-daily 30 --keep-monthly 12
