#!/bin/bash
set -e

die() {
    echo "$@" 1>&2
    exit 1
}

cd $(dirname $0)
test -d .git || die "Could not find git repository"
test -f target/archive/dists/unstable/InRelease || die "Could not find archive InRelease file, build first"

cd target/archive
git init --initial-branch debian-archive .
git add .
git commit -am 'Compiled Debian archive'
git push -f git@github.com:joshtriplett/josh-meta debian-archive
